import { GameType } from 'services/rawg';

export const fakeHeroGames: GameType[] = [
  {
    id: 1,
    name: 'God of War',
    slug: 'god-of-war-2',
    metacritc: 94,
    rating: 4.6,
    publishers: [{ slug: 'sony', name: 'Sony Interactive Entertainment' }],
    genres: [
      { slug: 'action', name: 'Action' },
      { slug: 'adventure', name: 'Adventure' },
    ],
    released: '',
    updated: '',
    description_raw: '',
    background_image_additional: '',
    screenshots: [],
    series: [],
    stores: [],
    website: '',
    background_image:
      'https://media.rawg.io/media/games/4be/4be6a6ad0364751a96229c56bf69be59.jpg',
    developers: [{ slug: 'sony', name: 'Sony Interactive Developers' }],
    parent_platforms: [{ platform: { slug: 'pc', name: 'pc' } }],
  },
  {
    id: 2,
    name: 'Minecraft',
    slug: 'minecraft',
    metacritc: 83,
    rating: 4.43,
    publishers: [{ slug: 'microsoft-studios', name: 'Microsoft Studios' }],
    genres: [
      { slug: 'action', name: 'Action' },
      { slug: 'adventure', name: 'Adventure' },
      { slug: 'simulation', name: 'Simulation' },
      { slug: 'arcade', name: 'Arcade' },
    ],
    released: '',
    updated: '',
    description_raw: '',
    background_image_additional: '',
    screenshots: [],
    series: [],
    stores: [],
    website: '',
    background_image:
      'https://media.rawg.io/media/games/b4e/b4e4c73d5aa4ec66bbf75375c4847a2b.jpg',
    developers: [{ slug: 'mojang', name: 'Mojang' }],
    parent_platforms: [{ platform: { slug: 'pc', name: 'Pc' } }],
  },
  {
    id: 3,
    name: 'Dark Souls III',
    slug: 'dark-souls-iii',
    metacritc: 89,
    rating: 4.4,
    publishers: [
      {
        slug: 'bandai-namco-entertainment',
        name: 'Bandai Namco Entertainment',
      },
    ],
    genres: [
      { slug: 'action', name: 'Action' },
      { slug: 'role-playing-games-rpg', name: 'RPG' },
    ],
    released: '',
    updated: '',
    description_raw: '',
    background_image_additional: '',
    screenshots: [],
    series: [],
    stores: [],
    website: '',
    background_image:
      'https://media.rawg.io/media/games/da1/da1b267764d77221f07a4386b6548e5a.jpg',
    developers: [{ slug: 'fromsoftware', name: 'FromSoftware' }],
    parent_platforms: [{ platform: { slug: 'pc', name: 'Pc' } }],
  },
];
